apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nkxt6fbak-nodejs 
  janus-idp.io/tekton: nkxt6fbak-nodejs
  backstage.io/kubernetes-id: nkxt6fbak-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nkxt6fbak-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  