apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nkxt6fbak-nodejs
  janus-idp.io/tekton: nkxt6fbak-nodejs
  backstage.io/kubernetes-id: nkxt6fbak-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nkxt6fbak-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
