apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nkxt6fbak-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nkxt6fbak-nodejs 
  name: nkxt6fbak-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nkxt6fbak-nodejs 
